# =========================================================================
# Olist E-Commerce SQL Analysis
# Database: olist_ecommerce.db
# Domain: Customers
# Script: new_vs_returning_revenue.py
# Objective: Compare monthly GMV generated by new and
# returning customers in the Olist E-Commerce dataset
# =========================================================================

from helper.utils import run_query

sql = """
WITH first_purchase AS (
    SELECT
        c.customer_unique_id,
        MIN(DATE(o.order_purchase_timestamp)) AS first_purchase_date
    FROM olist_customers_dataset AS c
    JOIN olist_orders_dataset AS o
        ON c.customer_id = o.customer_id
    WHERE o.order_status = 'delivered'
    GROUP BY c.customer_unique_id
),

order_revenue AS (
    SELECT
        o.order_id,
        c.customer_unique_id,
        DATE(o.order_purchase_timestamp) AS order_date,
        strftime('%Y-%m', o.order_purchase_timestamp) AS order_month,
        ROUND(SUM(oi.price + oi.freight_value), 2) AS order_gmv
    FROM olist_orders_dataset AS o
    JOIN olist_customers_dataset AS c
        ON o.customer_id = c.customer_id
    JOIN olist_order_items_dataset AS oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY
        o.order_id,
        c.customer_unique_id,
        order_date,
        order_month
)

SELECT
    o.order_month,
    ROUND(
        SUM(
            CASE
                WHEN strftime('%Y-%m', o.order_date) =
                     strftime('%Y-%m', fp.first_purchase_date)
                THEN o.order_gmv
                ELSE 0
            END
        ),
        2
    ) AS new_customer_gmv,

    ROUND(
        SUM(
            CASE
                WHEN strftime('%Y-%m', o.order_date) <>
                     strftime('%Y-%m', fp.first_purchase_date)
                THEN o.order_gmv
                ELSE 0
            END
        ),
        2
    ) AS returning_customer_gmv

FROM order_revenue AS o
JOIN first_purchase AS fp
    ON o.customer_unique_id = fp.customer_unique_id

GROUP BY o.order_month
ORDER BY o.order_month;
"""

run_query("New vs Returning Customer Revenue by Month", sql, preview_rows=10)
