"""
================================================================================
Olist E-Commerce Analysis Project
Module: analysis/02_eda.py

Objective:
    Performs exploratory data analysis (EDA) on the cleaned Olist datasets to
    answer key business questions through data
    visualizations. This module explores sales performance, customer behavior,
    logistics, product trends, payment patterns, and customer satisfaction to
    uncover actionable business insights.

Key Operations:
    - Load cleaned datasets exported from the data cleaning pipeline
    - Analyze sales and revenue trends over time
    - Explore product category performance
    - Examine price and freight value distributions
    - Visualize customer, payment, and order characteristics
    - Investigate relationships between key business variables
    - Generate publication-ready charts for reporting and Power BI

Data Source:
    Cleaned CSV datasets (exports/cleaned/)
    Generated by: analysis/01_data_cleaning.py

Outputs:
    - Exploratory data visualizations
    - Figures saved to plots/ for project documentation

Project Pipeline:
    01_data_cleaning.py
        ↓
    02_eda.py
        ↓
    03_delivery_outlier_investigation.py
        ↓
    SQL Analysis (Phase 3)
        ↓
    export_powerbi_data.py
        ↓
    Power BI Dashboard
================================================================================
"""

from matplotlib import pyplot as plt
from matplotlib.ticker import FuncFormatter
import seaborn as sns
import pandas as pd

# Load orders_clean.csv
orders_clean = pd.read_csv(
    "exports/cleaned/orders_clean.csv",
    parse_dates=[
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
    ],
)

# Load items_clean.csv
items_clean = pd.read_csv(
    "exports/cleaned/items_clean.csv", parse_dates=["shipping_limit_date"]
)

# Load products_clean.csv
products_clean = pd.read_csv("exports/cleaned/products_clean.csv")

# Load reviews_clean.csv
reviews_clean = pd.read_csv(
    "exports/cleaned/reviews_clean.csv",
    parse_dates=["review_creation_date", "review_answer_timestamp"],
)

customers_raw = pd.read_csv("data/olist_customers_dataset.csv")

# =====================================================================================
# Chart 1 · Monthly Revenue Trend (Line Chart)
# =====================================================================================
# df = pd.merge(items_clean, orders_clean, on="order_id")
# df = df[df["order_status"] == "delivered"]

# monthly_revenue = (
#     df.assign(GMV=df["price"] + df["freight_value"])
#     .groupby(df["order_purchase_timestamp"].dt.to_period("M"))["GMV"]
#     .sum()
#     .reset_index()
# )

# monthly_revenue["order_purchase_timestamp"] = monthly_revenue[
#     "order_purchase_timestamp"
# ].dt.to_timestamp()

# fig, ax = plt.subplots(figsize=(10, 5))

# sns.lineplot(
#     data=monthly_revenue, x="order_purchase_timestamp", y="GMV", marker="o", ax=ax
# )

# ax.set_title("Monthly Revenue Trend")
# ax.set_xlabel("Month")
# ax.set_ylabel("Revenue")
# ax.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"${x:,.0f}"))

# plt.tight_layout()
# plt.savefig("plots/monthly_revenue_trend.png", dpi=150)
# plt.show()

# =====================================================================================
# Chart 2 · Order Status Distribution (Bar Chart)
# =====================================================================================
# fig, ax = plt.subplots()

# # Sort by count and plot
# order = orders_clean["order_status"].value_counts().index
# sns.countplot(
#     data=orders_clean,
#     x="order_status",
#     order=order,
#     color="steelblue",
#     palette="Blues_d",
#     ax=ax,
# )

# # Add labels with commas
# for container in ax.containers:
#     ax.bar_label(container, padding=3)

# ax.set_title("Distribution of Order Statuses", fontsize=14, fontweight="bold", pad=20)
# ax.set_xlabel("Order Status", fontsize=12)
# ax.set_ylabel("Number of Orders", fontsize=12)

# # Rotate x-labels
# ax.tick_params(axis="x", rotation=45)

# plt.tight_layout()
# plt.savefig("plots/order_status_distribution.png", dpi=150)
# plt.show()

# =====================================================================================
# Chart 3 · Review Score Distribution (Bar Chart)
# =====================================================================================
# fig, ax = plt.subplots(figsize=(8, 5))

# order = reviews_clean["review_score"].value_counts().index
# sns.countplot(
#     data=reviews_clean,
#     x="review_score",
#     order=order,
#     color="steelblue",
#     palette="Blues_d",
#     ax=ax,
# )

# for container in ax.containers:
#     ax.bar_label(container, padding=3)

# ax.set_title("Review Score Distribution", fontsize=14, fontweight="bold", pad=20)
# ax.set_xlabel("Review Score", fontsize=12)
# ax.set_ylabel("Number of Reviews", fontsize=12)

# plt.tight_layout()
# plt.savefig("plots/review_score_distribution.png", dpi=150)
# plt.show()

# =====================================================================================
# Chart 4 · Top Product Categories by Revenue (GMV) (Horizontal Bar Chart)
# =====================================================================================
# filtered = items_clean.merge(orders_clean, on="order_id", how="inner").merge(
#     products_clean, on="product_id", how="inner"
# )

# filtered = filtered[filtered["order_status"] == "delivered"]

# filtered["total_revenue_gmv"] = filtered["price"] + filtered["freight_value"]

# grouped = (
#     filtered.groupby("product_category_name_english", as_index=False)[
#         "total_revenue_gmv"
#     ]
#     .sum()
#     .rename(columns={"product_category_name_english": "category_name"})
# )

# grouped["total_revenue_gmv"] = grouped["total_revenue_gmv"].round(2)

# result = grouped.sort_values("total_revenue_gmv", ascending=False).head(10)

# # --- Format category names ---
# result["category_name_formatted"] = (
#     result["category_name"]
#     .str.replace("_", " ")
#     .str.title()
#     .str.replace(" And ", " & ")
#     .str.replace(" Of ", " of ")
# )


# # --- Format revenue values ---
# def format_revenue(x, pos):
#     # Convert to millions if values are large (e.g., 1.2M)
#     if x >= 1e6:
#         return f"${x/1e6:.1f}M"
#     # Convert to thousands if values are medium (e.g., 1.2K)
#     elif x >= 1e3:
#         return f"${x/1e3:.1f}K"
#     # Default: Show as-is with 2 decimal places
#     else:
#         return f"${x:.2f}"


# # Apply FuncFormatter to the x-axis
# revenue_formatter = FuncFormatter(format_revenue)

# fig, ax = plt.subplots(figsize=(10, 6))

# sns.barplot(
#     x="total_revenue_gmv",
#     y="category_name_formatted",
#     hue="category_name_formatted",
#     data=result,
#     palette="viridis",
#     legend=False,
#     ax=ax,
# )

# ax.xaxis.set_major_formatter(revenue_formatter)
# for bar in ax.patches:
#     width = bar.get_width()

#     ax.text(
#         width + 5000,
#         bar.get_y() + bar.get_height() / 2,
#         f"${width/1_000_000:.2f}M",
#         va="center",
#         fontsize=10,
#     )

# ax.set_title(
#     "Top Product Categories by Revenue", fontsize=14, fontweight="bold", pad=20
# )
# ax.set_ylabel("Categories", fontsize=12)
# ax.set_xlabel("Revenue", fontsize=12)
# ax.set_xlim(0, result["total_revenue_gmv"].max() * 1.15)

# ax.grid(axis="x", linestyle="--", alpha=0.6)

# plt.tight_layout()
# plt.savefig("plots/top_product_categories_revenue.png", dpi=150)
# plt.show()

# =====================================================================================
# Chart 5 · Customer Geographic Distribution (State Level Horizontal Bar Chart)
# =====================================================================================
# result = (
#     customers_raw.groupby("customer_state")["customer_unique_id"]
#     .nunique()
#     .reset_index()
#     .rename(columns={"customer_unique_id": "unique_customer_count"})
#     .sort_values(by="unique_customer_count", ascending=False)
# )

# fig, ax = plt.subplots(figsize=(10, 6))

# sns.barplot(
#     x="unique_customer_count",
#     y="customer_state",
#     data=result,
#     color="#4C72B0",
#     ax=ax,
# )

# ax.xaxis.set_major_formatter(FuncFormatter(lambda x, _: f"{int(x):,}"))
# for bar in ax.patches:
#     width = bar.get_width()

#     ax.text(
#         width + 200,
#         bar.get_y() + bar.get_height() / 2,
#         f"{int(width):,}",
#         va="center",
#         ha="left",
#         fontsize=10,
#     )

# ax.set_title(
#     "Customer State Level Geographic Distribution",
#     fontsize=14,
#     fontweight="bold",
#     pad=20,
# )
# ax.set_ylabel("States", fontsize=12)
# ax.set_xlabel("Customer Counts", fontsize=12)

# ax.grid(axis="x", linestyle="--", alpha=0.6)

# plt.tight_layout()
# plt.savefig("plots/customer_state_distribution.png", dpi=150)
# plt.show()

# =====================================================================================
# Chart 6 · Price and Freight Value Distributions (Histograms + Boxplots for Outliers)
# =====================================================================================
"""
To improve readability, this histogram displays prices, and freight values up to the 99th percentile. 
Extreme values are excluded only from the visualization and are analyzed separately using the boxplot.
"""

# ==============================
# Price Distribution Histogram
# ==============================

# Calculate the 99th percentile
# price_limit = items_clean["price"].quantile(0.99)

# Filter only for visualization
# price_zoomed = items_clean[items_clean["price"] <= price_limit]

# fig, ax = plt.subplots(figsize=(10, 6))

# sns.histplot(
#     data=price_zoomed,
#     x="price",
#     kde=True,
#     edgecolor="gray",
#     linewidth=0.4,
#     bins=40,
#     color="#4C72B0",
#     ax=ax,
# )
# ax.xaxis.set_major_formatter(FuncFormatter(lambda x, _: f"R${x:,.0f}"))

# ax.set_title(
#     "Product Price Distribution (Up to 99th Percentile)",
#     fontsize=14,
#     fontweight="bold",
#     pad=20,
# )
# ax.set_xlabel("Product Price (R$)", fontsize=12)
# ax.set_ylabel("Number of Orders", fontsize=12)

# sns.despine()
# plt.tight_layout()
# plt.savefig("plots/price_distribution_histogram.png", dpi=150)
# plt.show()

# ======================================
# Freight Value Distribution Histogram
# ======================================
# Calculate the 99th percentile
# freight_limit = items_clean["freight_value"].quantile(0.99)

# Filter only for visualization
# freight_zoomed = items_clean[items_clean["freight_value"] <= freight_limit]

# fig, ax = plt.subplots(figsize=(10, 6))

# sns.histplot(
#     data=freight_zoomed,
#     x="freight_value",
#     bins=40,
#     kde=True,
#     color="#4C72B0",
#     edgecolor="gray",
#     linewidth=0.4,
#     ax=ax,
# )

# ax.set_title(
#     "Freight Value Distribution (Up to 99th Percentile)",
#     fontsize=14,
#     fontweight="bold",
#     pad=20,
# )
# ax.set_xlabel("Freight Value (R$)", fontsize=12)
# ax.set_ylabel("Number of Orders", fontsize=12)

# ax.xaxis.set_major_formatter(FuncFormatter(lambda x, _: f"R${x:,.0f}"))

# sns.despine()
# plt.tight_layout()
# plt.savefig("plots/freight_value_distribution_histogram.png", dpi=150)
# plt.show()

# ============================
# Price Distribution Boxplot
# ============================
# fig, ax = plt.subplots(figsize=(10, 2.5))

# sns.boxplot(
#     data=items_clean,
#     x="price",
#     color="#4C72B0",
#     width=0.5,
#     flierprops={
#         "marker": "o",
#         "markersize": 3,
#         "markerfacecolor": "red",
#         "markeredgecolor": "red",
#         "alpha": 0.4,
#     },
#     ax=ax,
# )

# ax.set_title(
#     "Product Price Distribution (Boxplot)", fontsize=14, fontweight="bold", pad=20
# )
# ax.set_xlabel("Product Price (R$)", fontsize=12)

# ax.xaxis.set_major_formatter(FuncFormatter(lambda x, _: f"R${x:,.0f}"))

# sns.despine(left=True)
# plt.tight_layout()
# plt.savefig("plots/price_distribution_boxplot.png", dpi=150)
# plt.show()

# ===================================
# Freight Value Distribution Boxplot
# ===================================
# fig, ax = plt.subplots(figsize=(10, 2.5))

# sns.boxplot(
#     data=items_clean,
#     x="freight_value",
#     color="#4C72B0",
#     width=0.5,
#     flierprops={
#         "marker": "o",
#         "markersize": 3,
#         "markerfacecolor": "red",
#         "markeredgecolor": "red",
#         "alpha": 0.4,
#     },
#     ax=ax,
# )

# ax.set_title(
#     "Freight Value Distribution (Boxplot)", fontsize=14, fontweight="bold", pad=20
# )
# ax.set_xlabel("Freight Value (R$)", fontsize=12)

# ax.xaxis.set_major_formatter(FuncFormatter(lambda x, _: f"R${x:,.0f}"))

# sns.despine(left=True)
# plt.tight_layout()
# plt.savefig("plots/freight_value_distribution_boxplot.png", dpi=150)
# plt.show()

# =====================================================================================
# Chart 7 · Delivery Performance Analysis
# =====================================================================================

# ===========================================================
# Distribution of Actual Delivery Time (Purchase → Delivery)
# ===========================================================

# Keep only delivered orders with valid delivery dates
# delivered_orders = orders_clean[
#     (orders_clean["order_status"] == "delivered")
#     & (orders_clean["order_delivered_customer_date"].notna())
# ].copy()

# # Calculate delivery time in days
# delivered_orders["delivery_time_days"] = (
#     delivered_orders["order_delivered_customer_date"]
#     - delivered_orders["order_purchase_timestamp"]
# ).dt.days

# fig, ax = plt.subplots(figsize=(10, 6))

# sns.histplot(
#     data=delivered_orders, x="delivery_time_days", bins=30, kde=True, color="steelblue"
# )

# ax.set_title(
#     "Distribution of Actual Delivery Time", fontsize=14, fontweight="bold", pad=20
# )
# ax.set_xlabel("Delivery Time (Days)", fontsize=12)
# ax.set_ylabel("Number of Orders", fontsize=12)

# plt.tight_layout()
# plt.savefig("plots/delivery_time_distribution.png", dpi=150)
# plt.show()

# ===============================================================
# Distribution of Delivery Delay (Actual vs. Estimated Delivery)
# ===============================================================

# Keep only delivered orders
# delivered_orders = orders_clean[
#     (orders_clean["order_status"] == "delivered")
#     & (orders_clean["order_delivered_customer_date"].notna())
# ].copy()

# # Calculate delivery delay in days
# delivered_orders["delivery_delay_days"] = (
#     delivered_orders["order_delivered_customer_date"]
#     - delivered_orders["order_estimated_delivery_date"]
# ).dt.days

# fig, ax = plt.subplots(figsize=(10, 6))

# sns.histplot(
#     data=delivered_orders,
#     x="delivery_delay_days",
#     bins=30,
#     kde=True,
#     color="tomato",
#     ax=ax,
# )

# # Reference line for on-time delivery
# ax.axvline(x=0, color="black", linestyle="--", linewidth=1.5, label="On-Time Delivery")

# ax.set_title("Distribution of Delivery Delay", fontsize=14, fontweight="bold", pad=20)
# ax.set_xlabel("Delivery Delay (Days)", fontsize=12)
# ax.set_ylabel("Number of Orders", fontsize=12)
# ax.legend()

# plt.tight_layout()
# plt.savefig("plots/delivery_delay_distribution.png", dpi=150)
# plt.show()

# =====================================================================================
# Chart 8 · Correlation Check: Delivery Time vs. Review Score (Scatter Plot)
# =====================================================================================
# merged_data = orders_clean.merge(reviews_clean, on="order_id", how="left")

# delivered_orders = merged_data[
#     (merged_data["order_status"] == "delivered")
#     & (merged_data["order_delivered_customer_date"].notna())
# ].copy()

# delivered_orders["delivery_delay_days"] = (
#     delivered_orders["order_delivered_customer_date"]
#     - delivered_orders["order_estimated_delivery_date"]
# ).dt.days

# delivered_orders = delivered_orders.dropna(
#     subset=["delivery_delay_days", "review_score"]
# )

# correlation = delivered_orders["delivery_delay_days"].corr(
#     delivered_orders["review_score"]
# )

# fig, ax = plt.subplots(figsize=(10, 6))

# ax.scatter(
#     data=delivered_orders, x="delivery_delay_days", y="review_score", alpha=0.2, s=15
# )

# fig.text(
#     0.75,
#     0.95,
#     f"Pearson r: {correlation:.2f}",
#     fontsize=14,
#     fontweight="bold",
#     verticalalignment="center",
#     bbox=dict(
#         boxstyle="round,pad=0.5",
#         facecolor="lightyellow",
#         edgecolor="darkred",
#         linewidth=2,
#         alpha=0.9,
#     ),
# )

# ax.set_title("Delivery Delay vs Review Score", fontsize=14, fontweight="bold", pad=20)
# ax.set_xlabel("Delivery Delay (Days)", fontsize=12)
# ax.set_ylabel("Review Score", fontsize=12)

# ax.set_yticks([1, 2, 3, 4, 5])

# ax.grid(alpha=0.3)

# plt.tight_layout()
# plt.savefig("plots/delivery_delay_vs_review_score.png", dpi=150)
# plt.show()
