"""
================================================================================
Olist E-Commerce Analysis Project
Module: analysis/03_delivery_outlier_investigation.py

Objective:
    Investigates extreme delivery time and delivery delay outliers identified
    during exploratory data analysis. This module validates whether unusual
    delivery records represent genuine business events, data quality issues,
    or exceptional logistics cases by examining order, customer, seller,
    product, and review information.

Key Operations:
    - Load cleaned datasets exported from the data cleaning pipeline
    - Identify orders with extreme delivery times and delivery delays
    - Examine unusually early and significantly late deliveries
    - Investigate relationships between delivery anomalies and review scores
    - Analyze seller, customer, and product characteristics of outlier orders
    - Differentiate legitimate business outliers from potential data issues
    - Document findings to support business insights and reporting

Data Source:
    Cleaned CSV datasets (exports/cleaned/)
    Generated by: analysis/01_data_cleaning.py

Outputs:
    - Investigation summaries of delivery outliers
    - Supporting visualizations and tables
    - Figures saved to plots/investigations/ for project documentation

Project Pipeline:
    01_data_cleaning.py
        ↓
    02_eda.py
        ↓
    03_delivery_outlier_investigation.py
        ↓
    SQL Analysis (Phase 3)
        ↓
    export_powerbi_data.py
        ↓
    Power BI Dashboard

================================================================================
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect("olist_ecommerce.db")
df = pd.read_sql_query(
    """
    SELECT 
    o.order_id,
    o.customer_id,
    oi.seller_id,
    p.product_category_name,
    r.review_score,
    r.review_comment_message,  -- Crucial for sentiment analysis
    o.order_purchase_timestamp,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date,
    -- Calculate delay in days
    JULIANDAY(o.order_delivered_customer_date) - JULIANDAY(o.order_estimated_delivery_date) AS delivery_delay_days
FROM olist_orders_dataset o
JOIN olist_order_reviews_dataset r ON o.order_id = r.order_id
JOIN olist_order_items_dataset oi ON o.order_id = oi.order_id
LEFT JOIN olist_products_dataset p ON oi.product_id = p.product_id
WHERE o.order_status = 'delivered'
AND r.review_score = 5
AND (JULIANDAY(o.order_delivered_customer_date) - JULIANDAY(o.order_estimated_delivery_date)) > 100;
""",
    conn,
)
df.to_csv("exports/investigation/outlier_late_deliveries.csv", index=False)

df2 = pd.read_sql_query(
    """
SELECT 
    o.order_id,
    o.order_purchase_timestamp,
    o.order_approved_at,
    o.order_delivered_carrier_date,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date,
    JULIANDAY(o.order_delivered_customer_date) - JULIANDAY(o.order_estimated_delivery_date) AS delivery_delay_days
FROM olist_orders_dataset o
WHERE o.order_status = 'delivered'
AND (JULIANDAY(o.order_delivered_customer_date) - JULIANDAY(o.order_estimated_delivery_date)) < -100;
""",
    conn,
)
df2.to_csv("exports/investigation/outlier_early_deliveries.csv", index=False)
